package test.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adm_id
     *
     * @mbg.generated
     */
    private String admId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adm_name
     *
     * @mbg.generated
     */
    private String admName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adm_sexual
     *
     * @mbg.generated
     */
    private Integer admSexual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.us_id
     *
     * @mbg.generated
     */
    private String usId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adm_state
     *
     * @mbg.generated
     */
    private Integer admState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adm_city
     *
     * @mbg.generated
     */
    private String admCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adm_address
     *
     * @mbg.generated
     */
    private String admAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adm_password
     *
     * @mbg.generated
     */
    private String admPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adm_phone
     *
     * @mbg.generated
     */
    private String admPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adm_remarks
     *
     * @mbg.generated
     */
    private String admRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adm_id
     *
     * @return the value of admin.adm_id
     *
     * @mbg.generated
     */
    public String getAdmId() {
        return admId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adm_id
     *
     * @param admId the value for admin.adm_id
     *
     * @mbg.generated
     */
    public void setAdmId(String admId) {
        this.admId = admId == null ? null : admId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adm_name
     *
     * @return the value of admin.adm_name
     *
     * @mbg.generated
     */
    public String getAdmName() {
        return admName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adm_name
     *
     * @param admName the value for admin.adm_name
     *
     * @mbg.generated
     */
    public void setAdmName(String admName) {
        this.admName = admName == null ? null : admName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adm_sexual
     *
     * @return the value of admin.adm_sexual
     *
     * @mbg.generated
     */
    public Integer getAdmSexual() {
        return admSexual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adm_sexual
     *
     * @param admSexual the value for admin.adm_sexual
     *
     * @mbg.generated
     */
    public void setAdmSexual(Integer admSexual) {
        this.admSexual = admSexual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.us_id
     *
     * @return the value of admin.us_id
     *
     * @mbg.generated
     */
    public String getUsId() {
        return usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.us_id
     *
     * @param usId the value for admin.us_id
     *
     * @mbg.generated
     */
    public void setUsId(String usId) {
        this.usId = usId == null ? null : usId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adm_state
     *
     * @return the value of admin.adm_state
     *
     * @mbg.generated
     */
    public Integer getAdmState() {
        return admState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adm_state
     *
     * @param admState the value for admin.adm_state
     *
     * @mbg.generated
     */
    public void setAdmState(Integer admState) {
        this.admState = admState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adm_city
     *
     * @return the value of admin.adm_city
     *
     * @mbg.generated
     */
    public String getAdmCity() {
        return admCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adm_city
     *
     * @param admCity the value for admin.adm_city
     *
     * @mbg.generated
     */
    public void setAdmCity(String admCity) {
        this.admCity = admCity == null ? null : admCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adm_address
     *
     * @return the value of admin.adm_address
     *
     * @mbg.generated
     */
    public String getAdmAddress() {
        return admAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adm_address
     *
     * @param admAddress the value for admin.adm_address
     *
     * @mbg.generated
     */
    public void setAdmAddress(String admAddress) {
        this.admAddress = admAddress == null ? null : admAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adm_password
     *
     * @return the value of admin.adm_password
     *
     * @mbg.generated
     */
    public String getAdmPassword() {
        return admPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adm_password
     *
     * @param admPassword the value for admin.adm_password
     *
     * @mbg.generated
     */
    public void setAdmPassword(String admPassword) {
        this.admPassword = admPassword == null ? null : admPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adm_phone
     *
     * @return the value of admin.adm_phone
     *
     * @mbg.generated
     */
    public String getAdmPhone() {
        return admPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adm_phone
     *
     * @param admPhone the value for admin.adm_phone
     *
     * @mbg.generated
     */
    public void setAdmPhone(String admPhone) {
        this.admPhone = admPhone == null ? null : admPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adm_remarks
     *
     * @return the value of admin.adm_remarks
     *
     * @mbg.generated
     */
    public String getAdmRemarks() {
        return admRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adm_remarks
     *
     * @param admRemarks the value for admin.adm_remarks
     *
     * @mbg.generated
     */
    public void setAdmRemarks(String admRemarks) {
        this.admRemarks = admRemarks == null ? null : admRemarks.trim();
    }
}