package test.entity;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cit_id
     *
     * @mbg.generated
     */
    private String citId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cit_name
     *
     * @mbg.generated
     */
    private String citName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.pro_id
     *
     * @mbg.generated
     */
    private String proId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cit_id
     *
     * @return the value of city.cit_id
     *
     * @mbg.generated
     */
    public String getCitId() {
        return citId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cit_id
     *
     * @param citId the value for city.cit_id
     *
     * @mbg.generated
     */
    public void setCitId(String citId) {
        this.citId = citId == null ? null : citId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cit_name
     *
     * @return the value of city.cit_name
     *
     * @mbg.generated
     */
    public String getCitName() {
        return citName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cit_name
     *
     * @param citName the value for city.cit_name
     *
     * @mbg.generated
     */
    public void setCitName(String citName) {
        this.citName = citName == null ? null : citName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.pro_id
     *
     * @return the value of city.pro_id
     *
     * @mbg.generated
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.pro_id
     *
     * @param proId the value for city.pro_id
     *
     * @mbg.generated
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }
}