package test.entity;

import java.util.Date;

public class Consumer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.con_id
     *
     * @mbg.generated
     */
    private String conId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.con_name
     *
     * @mbg.generated
     */
    private String conName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.con_sexual
     *
     * @mbg.generated
     */
    private Integer conSexual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.us_id
     *
     * @mbg.generated
     */
    private String usId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.con_password
     *
     * @mbg.generated
     */
    private String conPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.con_phone
     *
     * @mbg.generated
     */
    private String conPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.con_birth
     *
     * @mbg.generated
     */
    private Date conBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.con_address
     *
     * @mbg.generated
     */
    private String conAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.con_remarks
     *
     * @mbg.generated
     */
    private String conRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.con_id
     *
     * @return the value of consumer.con_id
     *
     * @mbg.generated
     */
    public String getConId() {
        return conId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.con_id
     *
     * @param conId the value for consumer.con_id
     *
     * @mbg.generated
     */
    public void setConId(String conId) {
        this.conId = conId == null ? null : conId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.con_name
     *
     * @return the value of consumer.con_name
     *
     * @mbg.generated
     */
    public String getConName() {
        return conName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.con_name
     *
     * @param conName the value for consumer.con_name
     *
     * @mbg.generated
     */
    public void setConName(String conName) {
        this.conName = conName == null ? null : conName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.con_sexual
     *
     * @return the value of consumer.con_sexual
     *
     * @mbg.generated
     */
    public Integer getConSexual() {
        return conSexual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.con_sexual
     *
     * @param conSexual the value for consumer.con_sexual
     *
     * @mbg.generated
     */
    public void setConSexual(Integer conSexual) {
        this.conSexual = conSexual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.us_id
     *
     * @return the value of consumer.us_id
     *
     * @mbg.generated
     */
    public String getUsId() {
        return usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.us_id
     *
     * @param usId the value for consumer.us_id
     *
     * @mbg.generated
     */
    public void setUsId(String usId) {
        this.usId = usId == null ? null : usId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.con_password
     *
     * @return the value of consumer.con_password
     *
     * @mbg.generated
     */
    public String getConPassword() {
        return conPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.con_password
     *
     * @param conPassword the value for consumer.con_password
     *
     * @mbg.generated
     */
    public void setConPassword(String conPassword) {
        this.conPassword = conPassword == null ? null : conPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.con_phone
     *
     * @return the value of consumer.con_phone
     *
     * @mbg.generated
     */
    public String getConPhone() {
        return conPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.con_phone
     *
     * @param conPhone the value for consumer.con_phone
     *
     * @mbg.generated
     */
    public void setConPhone(String conPhone) {
        this.conPhone = conPhone == null ? null : conPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.con_birth
     *
     * @return the value of consumer.con_birth
     *
     * @mbg.generated
     */
    public Date getConBirth() {
        return conBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.con_birth
     *
     * @param conBirth the value for consumer.con_birth
     *
     * @mbg.generated
     */
    public void setConBirth(Date conBirth) {
        this.conBirth = conBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.con_address
     *
     * @return the value of consumer.con_address
     *
     * @mbg.generated
     */
    public String getConAddress() {
        return conAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.con_address
     *
     * @param conAddress the value for consumer.con_address
     *
     * @mbg.generated
     */
    public void setConAddress(String conAddress) {
        this.conAddress = conAddress == null ? null : conAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.con_remarks
     *
     * @return the value of consumer.con_remarks
     *
     * @mbg.generated
     */
    public String getConRemarks() {
        return conRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.con_remarks
     *
     * @param conRemarks the value for consumer.con_remarks
     *
     * @mbg.generated
     */
    public void setConRemarks(String conRemarks) {
        this.conRemarks = conRemarks == null ? null : conRemarks.trim();
    }
}