package test.entity;

public class DistributionScope {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_scope.distr_id
     *
     * @mbg.generated
     */
    private Integer distrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_scope.distr_name
     *
     * @mbg.generated
     */
    private String distrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_scope.distr_price
     *
     * @mbg.generated
     */
    private Long distrPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_scope.cit_id
     *
     * @mbg.generated
     */
    private String citId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution_scope.distr_remarks
     *
     * @mbg.generated
     */
    private String distrRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_scope.distr_id
     *
     * @return the value of distribution_scope.distr_id
     *
     * @mbg.generated
     */
    public Integer getDistrId() {
        return distrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_scope.distr_id
     *
     * @param distrId the value for distribution_scope.distr_id
     *
     * @mbg.generated
     */
    public void setDistrId(Integer distrId) {
        this.distrId = distrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_scope.distr_name
     *
     * @return the value of distribution_scope.distr_name
     *
     * @mbg.generated
     */
    public String getDistrName() {
        return distrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_scope.distr_name
     *
     * @param distrName the value for distribution_scope.distr_name
     *
     * @mbg.generated
     */
    public void setDistrName(String distrName) {
        this.distrName = distrName == null ? null : distrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_scope.distr_price
     *
     * @return the value of distribution_scope.distr_price
     *
     * @mbg.generated
     */
    public Long getDistrPrice() {
        return distrPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_scope.distr_price
     *
     * @param distrPrice the value for distribution_scope.distr_price
     *
     * @mbg.generated
     */
    public void setDistrPrice(Long distrPrice) {
        this.distrPrice = distrPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_scope.cit_id
     *
     * @return the value of distribution_scope.cit_id
     *
     * @mbg.generated
     */
    public String getCitId() {
        return citId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_scope.cit_id
     *
     * @param citId the value for distribution_scope.cit_id
     *
     * @mbg.generated
     */
    public void setCitId(String citId) {
        this.citId = citId == null ? null : citId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution_scope.distr_remarks
     *
     * @return the value of distribution_scope.distr_remarks
     *
     * @mbg.generated
     */
    public String getDistrRemarks() {
        return distrRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution_scope.distr_remarks
     *
     * @param distrRemarks the value for distribution_scope.distr_remarks
     *
     * @mbg.generated
     */
    public void setDistrRemarks(String distrRemarks) {
        this.distrRemarks = distrRemarks == null ? null : distrRemarks.trim();
    }
}