package test.entity;

public class Distribution {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.dis_id
     *
     * @mbg.generated
     */
    private Integer disId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.dis_name
     *
     * @mbg.generated
     */
    private String disName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.pro_id
     *
     * @mbg.generated
     */
    private String proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.cit_id
     *
     * @mbg.generated
     */
    private String citId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.adm_id
     *
     * @mbg.generated
     */
    private String admId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.dis_phone
     *
     * @mbg.generated
     */
    private String disPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.dis_address
     *
     * @mbg.generated
     */
    private String disAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.dis_remarks
     *
     * @mbg.generated
     */
    private String disRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.dis_id
     *
     * @return the value of distribution.dis_id
     *
     * @mbg.generated
     */
    public Integer getDisId() {
        return disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.dis_id
     *
     * @param disId the value for distribution.dis_id
     *
     * @mbg.generated
     */
    public void setDisId(Integer disId) {
        this.disId = disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.dis_name
     *
     * @return the value of distribution.dis_name
     *
     * @mbg.generated
     */
    public String getDisName() {
        return disName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.dis_name
     *
     * @param disName the value for distribution.dis_name
     *
     * @mbg.generated
     */
    public void setDisName(String disName) {
        this.disName = disName == null ? null : disName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.pro_id
     *
     * @return the value of distribution.pro_id
     *
     * @mbg.generated
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.pro_id
     *
     * @param proId the value for distribution.pro_id
     *
     * @mbg.generated
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.cit_id
     *
     * @return the value of distribution.cit_id
     *
     * @mbg.generated
     */
    public String getCitId() {
        return citId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.cit_id
     *
     * @param citId the value for distribution.cit_id
     *
     * @mbg.generated
     */
    public void setCitId(String citId) {
        this.citId = citId == null ? null : citId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.adm_id
     *
     * @return the value of distribution.adm_id
     *
     * @mbg.generated
     */
    public String getAdmId() {
        return admId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.adm_id
     *
     * @param admId the value for distribution.adm_id
     *
     * @mbg.generated
     */
    public void setAdmId(String admId) {
        this.admId = admId == null ? null : admId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.dis_phone
     *
     * @return the value of distribution.dis_phone
     *
     * @mbg.generated
     */
    public String getDisPhone() {
        return disPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.dis_phone
     *
     * @param disPhone the value for distribution.dis_phone
     *
     * @mbg.generated
     */
    public void setDisPhone(String disPhone) {
        this.disPhone = disPhone == null ? null : disPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.dis_address
     *
     * @return the value of distribution.dis_address
     *
     * @mbg.generated
     */
    public String getDisAddress() {
        return disAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.dis_address
     *
     * @param disAddress the value for distribution.dis_address
     *
     * @mbg.generated
     */
    public void setDisAddress(String disAddress) {
        this.disAddress = disAddress == null ? null : disAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.dis_remarks
     *
     * @return the value of distribution.dis_remarks
     *
     * @mbg.generated
     */
    public String getDisRemarks() {
        return disRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.dis_remarks
     *
     * @param disRemarks the value for distribution.dis_remarks
     *
     * @mbg.generated
     */
    public void setDisRemarks(String disRemarks) {
        this.disRemarks = disRemarks == null ? null : disRemarks.trim();
    }
}