package test.entity;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_id
     *
     * @mbg.generated
     */
    private String ordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_type
     *
     * @mbg.generated
     */
    private Integer ordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_number
     *
     * @mbg.generated
     */
    private String ordNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_product_name
     *
     * @mbg.generated
     */
    private String ordProductName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_weight
     *
     * @mbg.generated
     */
    private Integer ordWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_mailer
     *
     * @mbg.generated
     */
    private String ordMailer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_address
     *
     * @mbg.generated
     */
    private String ordAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_receiving
     *
     * @mbg.generated
     */
    private String ordReceiving;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_state
     *
     * @mbg.generated
     */
    private Integer ordState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_phone
     *
     * @mbg.generated
     */
    private String ordPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_consignee
     *
     * @mbg.generated
     */
    private String ordConsignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_con_phone
     *
     * @mbg.generated
     */
    private String ordConPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_start_city
     *
     * @mbg.generated
     */
    private String ordStartCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_midpoint_city
     *
     * @mbg.generated
     */
    private String ordMidpointCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_end_city
     *
     * @mbg.generated
     */
    private String ordEndCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_price
     *
     * @mbg.generated
     */
    private Long ordPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_transit_price
     *
     * @mbg.generated
     */
    private Long ordTransitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_total_price
     *
     * @mbg.generated
     */
    private Long ordTotalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_vehicle
     *
     * @mbg.generated
     */
    private String ordVehicle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ord_remarks
     *
     * @mbg.generated
     */
    private String ordRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_id
     *
     * @return the value of order.ord_id
     *
     * @mbg.generated
     */
    public String getOrdId() {
        return ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_id
     *
     * @param ordId the value for order.ord_id
     *
     * @mbg.generated
     */
    public void setOrdId(String ordId) {
        this.ordId = ordId == null ? null : ordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_type
     *
     * @return the value of order.ord_type
     *
     * @mbg.generated
     */
    public Integer getOrdType() {
        return ordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_type
     *
     * @param ordType the value for order.ord_type
     *
     * @mbg.generated
     */
    public void setOrdType(Integer ordType) {
        this.ordType = ordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_number
     *
     * @return the value of order.ord_number
     *
     * @mbg.generated
     */
    public String getOrdNumber() {
        return ordNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_number
     *
     * @param ordNumber the value for order.ord_number
     *
     * @mbg.generated
     */
    public void setOrdNumber(String ordNumber) {
        this.ordNumber = ordNumber == null ? null : ordNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_product_name
     *
     * @return the value of order.ord_product_name
     *
     * @mbg.generated
     */
    public String getOrdProductName() {
        return ordProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_product_name
     *
     * @param ordProductName the value for order.ord_product_name
     *
     * @mbg.generated
     */
    public void setOrdProductName(String ordProductName) {
        this.ordProductName = ordProductName == null ? null : ordProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_weight
     *
     * @return the value of order.ord_weight
     *
     * @mbg.generated
     */
    public Integer getOrdWeight() {
        return ordWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_weight
     *
     * @param ordWeight the value for order.ord_weight
     *
     * @mbg.generated
     */
    public void setOrdWeight(Integer ordWeight) {
        this.ordWeight = ordWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_mailer
     *
     * @return the value of order.ord_mailer
     *
     * @mbg.generated
     */
    public String getOrdMailer() {
        return ordMailer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_mailer
     *
     * @param ordMailer the value for order.ord_mailer
     *
     * @mbg.generated
     */
    public void setOrdMailer(String ordMailer) {
        this.ordMailer = ordMailer == null ? null : ordMailer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_address
     *
     * @return the value of order.ord_address
     *
     * @mbg.generated
     */
    public String getOrdAddress() {
        return ordAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_address
     *
     * @param ordAddress the value for order.ord_address
     *
     * @mbg.generated
     */
    public void setOrdAddress(String ordAddress) {
        this.ordAddress = ordAddress == null ? null : ordAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_receiving
     *
     * @return the value of order.ord_receiving
     *
     * @mbg.generated
     */
    public String getOrdReceiving() {
        return ordReceiving;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_receiving
     *
     * @param ordReceiving the value for order.ord_receiving
     *
     * @mbg.generated
     */
    public void setOrdReceiving(String ordReceiving) {
        this.ordReceiving = ordReceiving == null ? null : ordReceiving.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_state
     *
     * @return the value of order.ord_state
     *
     * @mbg.generated
     */
    public Integer getOrdState() {
        return ordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_state
     *
     * @param ordState the value for order.ord_state
     *
     * @mbg.generated
     */
    public void setOrdState(Integer ordState) {
        this.ordState = ordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_phone
     *
     * @return the value of order.ord_phone
     *
     * @mbg.generated
     */
    public String getOrdPhone() {
        return ordPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_phone
     *
     * @param ordPhone the value for order.ord_phone
     *
     * @mbg.generated
     */
    public void setOrdPhone(String ordPhone) {
        this.ordPhone = ordPhone == null ? null : ordPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_consignee
     *
     * @return the value of order.ord_consignee
     *
     * @mbg.generated
     */
    public String getOrdConsignee() {
        return ordConsignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_consignee
     *
     * @param ordConsignee the value for order.ord_consignee
     *
     * @mbg.generated
     */
    public void setOrdConsignee(String ordConsignee) {
        this.ordConsignee = ordConsignee == null ? null : ordConsignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_con_phone
     *
     * @return the value of order.ord_con_phone
     *
     * @mbg.generated
     */
    public String getOrdConPhone() {
        return ordConPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_con_phone
     *
     * @param ordConPhone the value for order.ord_con_phone
     *
     * @mbg.generated
     */
    public void setOrdConPhone(String ordConPhone) {
        this.ordConPhone = ordConPhone == null ? null : ordConPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_start_city
     *
     * @return the value of order.ord_start_city
     *
     * @mbg.generated
     */
    public String getOrdStartCity() {
        return ordStartCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_start_city
     *
     * @param ordStartCity the value for order.ord_start_city
     *
     * @mbg.generated
     */
    public void setOrdStartCity(String ordStartCity) {
        this.ordStartCity = ordStartCity == null ? null : ordStartCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_midpoint_city
     *
     * @return the value of order.ord_midpoint_city
     *
     * @mbg.generated
     */
    public String getOrdMidpointCity() {
        return ordMidpointCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_midpoint_city
     *
     * @param ordMidpointCity the value for order.ord_midpoint_city
     *
     * @mbg.generated
     */
    public void setOrdMidpointCity(String ordMidpointCity) {
        this.ordMidpointCity = ordMidpointCity == null ? null : ordMidpointCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_end_city
     *
     * @return the value of order.ord_end_city
     *
     * @mbg.generated
     */
    public String getOrdEndCity() {
        return ordEndCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_end_city
     *
     * @param ordEndCity the value for order.ord_end_city
     *
     * @mbg.generated
     */
    public void setOrdEndCity(String ordEndCity) {
        this.ordEndCity = ordEndCity == null ? null : ordEndCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_price
     *
     * @return the value of order.ord_price
     *
     * @mbg.generated
     */
    public Long getOrdPrice() {
        return ordPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_price
     *
     * @param ordPrice the value for order.ord_price
     *
     * @mbg.generated
     */
    public void setOrdPrice(Long ordPrice) {
        this.ordPrice = ordPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_transit_price
     *
     * @return the value of order.ord_transit_price
     *
     * @mbg.generated
     */
    public Long getOrdTransitPrice() {
        return ordTransitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_transit_price
     *
     * @param ordTransitPrice the value for order.ord_transit_price
     *
     * @mbg.generated
     */
    public void setOrdTransitPrice(Long ordTransitPrice) {
        this.ordTransitPrice = ordTransitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_total_price
     *
     * @return the value of order.ord_total_price
     *
     * @mbg.generated
     */
    public Long getOrdTotalPrice() {
        return ordTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_total_price
     *
     * @param ordTotalPrice the value for order.ord_total_price
     *
     * @mbg.generated
     */
    public void setOrdTotalPrice(Long ordTotalPrice) {
        this.ordTotalPrice = ordTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_vehicle
     *
     * @return the value of order.ord_vehicle
     *
     * @mbg.generated
     */
    public String getOrdVehicle() {
        return ordVehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_vehicle
     *
     * @param ordVehicle the value for order.ord_vehicle
     *
     * @mbg.generated
     */
    public void setOrdVehicle(String ordVehicle) {
        this.ordVehicle = ordVehicle == null ? null : ordVehicle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ord_remarks
     *
     * @return the value of order.ord_remarks
     *
     * @mbg.generated
     */
    public String getOrdRemarks() {
        return ordRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ord_remarks
     *
     * @param ordRemarks the value for order.ord_remarks
     *
     * @mbg.generated
     */
    public void setOrdRemarks(String ordRemarks) {
        this.ordRemarks = ordRemarks == null ? null : ordRemarks.trim();
    }
}