package test.entity;

public class Province {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pro_id
     *
     * @mbg.generated
     */
    private String proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pro_name
     *
     * @mbg.generated
     */
    private String proName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pro_id
     *
     * @return the value of province.pro_id
     *
     * @mbg.generated
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pro_id
     *
     * @param proId the value for province.pro_id
     *
     * @mbg.generated
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pro_name
     *
     * @return the value of province.pro_name
     *
     * @mbg.generated
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pro_name
     *
     * @param proName the value for province.pro_name
     *
     * @mbg.generated
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }
}