package test.entity;

public class Region {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.reg_id
     *
     * @mbg.generated
     */
    private String regId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.reg_name
     *
     * @mbg.generated
     */
    private String regName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.cit_id
     *
     * @mbg.generated
     */
    private String citId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.reg_id
     *
     * @return the value of region.reg_id
     *
     * @mbg.generated
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.reg_id
     *
     * @param regId the value for region.reg_id
     *
     * @mbg.generated
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.reg_name
     *
     * @return the value of region.reg_name
     *
     * @mbg.generated
     */
    public String getRegName() {
        return regName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.reg_name
     *
     * @param regName the value for region.reg_name
     *
     * @mbg.generated
     */
    public void setRegName(String regName) {
        this.regName = regName == null ? null : regName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.cit_id
     *
     * @return the value of region.cit_id
     *
     * @mbg.generated
     */
    public String getCitId() {
        return citId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.cit_id
     *
     * @param citId the value for region.cit_id
     *
     * @mbg.generated
     */
    public void setCitId(String citId) {
        this.citId = citId == null ? null : citId.trim();
    }
}