package test.entity;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.rou_id
     *
     * @mbg.generated
     */
    private String rouId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.rou_name
     *
     * @mbg.generated
     */
    private String rouName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.pro_id_start
     *
     * @mbg.generated
     */
    private String proIdStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.cit_id_start
     *
     * @mbg.generated
     */
    private String citIdStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.pro_id_midpoint
     *
     * @mbg.generated
     */
    private String proIdMidpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.cit_id_midpoint
     *
     * @mbg.generated
     */
    private String citIdMidpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.pro_id_end
     *
     * @mbg.generated
     */
    private String proIdEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.cit_id_end
     *
     * @mbg.generated
     */
    private String citIdEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.rou_price
     *
     * @mbg.generated
     */
    private Long rouPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.rou_remarks
     *
     * @mbg.generated
     */
    private String rouRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.rou_id
     *
     * @return the value of route.rou_id
     *
     * @mbg.generated
     */
    public String getRouId() {
        return rouId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.rou_id
     *
     * @param rouId the value for route.rou_id
     *
     * @mbg.generated
     */
    public void setRouId(String rouId) {
        this.rouId = rouId == null ? null : rouId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.rou_name
     *
     * @return the value of route.rou_name
     *
     * @mbg.generated
     */
    public String getRouName() {
        return rouName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.rou_name
     *
     * @param rouName the value for route.rou_name
     *
     * @mbg.generated
     */
    public void setRouName(String rouName) {
        this.rouName = rouName == null ? null : rouName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.pro_id_start
     *
     * @return the value of route.pro_id_start
     *
     * @mbg.generated
     */
    public String getProIdStart() {
        return proIdStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.pro_id_start
     *
     * @param proIdStart the value for route.pro_id_start
     *
     * @mbg.generated
     */
    public void setProIdStart(String proIdStart) {
        this.proIdStart = proIdStart == null ? null : proIdStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.cit_id_start
     *
     * @return the value of route.cit_id_start
     *
     * @mbg.generated
     */
    public String getCitIdStart() {
        return citIdStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.cit_id_start
     *
     * @param citIdStart the value for route.cit_id_start
     *
     * @mbg.generated
     */
    public void setCitIdStart(String citIdStart) {
        this.citIdStart = citIdStart == null ? null : citIdStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.pro_id_midpoint
     *
     * @return the value of route.pro_id_midpoint
     *
     * @mbg.generated
     */
    public String getProIdMidpoint() {
        return proIdMidpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.pro_id_midpoint
     *
     * @param proIdMidpoint the value for route.pro_id_midpoint
     *
     * @mbg.generated
     */
    public void setProIdMidpoint(String proIdMidpoint) {
        this.proIdMidpoint = proIdMidpoint == null ? null : proIdMidpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.cit_id_midpoint
     *
     * @return the value of route.cit_id_midpoint
     *
     * @mbg.generated
     */
    public String getCitIdMidpoint() {
        return citIdMidpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.cit_id_midpoint
     *
     * @param citIdMidpoint the value for route.cit_id_midpoint
     *
     * @mbg.generated
     */
    public void setCitIdMidpoint(String citIdMidpoint) {
        this.citIdMidpoint = citIdMidpoint == null ? null : citIdMidpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.pro_id_end
     *
     * @return the value of route.pro_id_end
     *
     * @mbg.generated
     */
    public String getProIdEnd() {
        return proIdEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.pro_id_end
     *
     * @param proIdEnd the value for route.pro_id_end
     *
     * @mbg.generated
     */
    public void setProIdEnd(String proIdEnd) {
        this.proIdEnd = proIdEnd == null ? null : proIdEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.cit_id_end
     *
     * @return the value of route.cit_id_end
     *
     * @mbg.generated
     */
    public String getCitIdEnd() {
        return citIdEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.cit_id_end
     *
     * @param citIdEnd the value for route.cit_id_end
     *
     * @mbg.generated
     */
    public void setCitIdEnd(String citIdEnd) {
        this.citIdEnd = citIdEnd == null ? null : citIdEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.rou_price
     *
     * @return the value of route.rou_price
     *
     * @mbg.generated
     */
    public Long getRouPrice() {
        return rouPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.rou_price
     *
     * @param rouPrice the value for route.rou_price
     *
     * @mbg.generated
     */
    public void setRouPrice(Long rouPrice) {
        this.rouPrice = rouPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.rou_remarks
     *
     * @return the value of route.rou_remarks
     *
     * @mbg.generated
     */
    public String getRouRemarks() {
        return rouRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.rou_remarks
     *
     * @param rouRemarks the value for route.rou_remarks
     *
     * @mbg.generated
     */
    public void setRouRemarks(String rouRemarks) {
        this.rouRemarks = rouRemarks == null ? null : rouRemarks.trim();
    }
}