package test.entity;

public class UserGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.us_id
     *
     * @mbg.generated
     */
    private String usId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.us_name
     *
     * @mbg.generated
     */
    private String usName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.us_remarks
     *
     * @mbg.generated
     */
    private String usRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.us_id
     *
     * @return the value of user_group.us_id
     *
     * @mbg.generated
     */
    public String getUsId() {
        return usId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.us_id
     *
     * @param usId the value for user_group.us_id
     *
     * @mbg.generated
     */
    public void setUsId(String usId) {
        this.usId = usId == null ? null : usId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.us_name
     *
     * @return the value of user_group.us_name
     *
     * @mbg.generated
     */
    public String getUsName() {
        return usName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.us_name
     *
     * @param usName the value for user_group.us_name
     *
     * @mbg.generated
     */
    public void setUsName(String usName) {
        this.usName = usName == null ? null : usName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.us_remarks
     *
     * @return the value of user_group.us_remarks
     *
     * @mbg.generated
     */
    public String getUsRemarks() {
        return usRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.us_remarks
     *
     * @param usRemarks the value for user_group.us_remarks
     *
     * @mbg.generated
     */
    public void setUsRemarks(String usRemarks) {
        this.usRemarks = usRemarks == null ? null : usRemarks.trim();
    }
}