package test.entity;

import java.util.Date;

public class Vehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.veh_id
     *
     * @mbg.generated
     */
    private String vehId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.veh_type
     *
     * @mbg.generated
     */
    private String vehType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.veh_address
     *
     * @mbg.generated
     */
    private String vehAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.rou_id
     *
     * @mbg.generated
     */
    private String rouId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.veh_birth
     *
     * @mbg.generated
     */
    private Date vehBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.veh_purchase_date
     *
     * @mbg.generated
     */
    private Date vehPurchaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.veh_remarks
     *
     * @mbg.generated
     */
    private String vehRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.veh_id
     *
     * @return the value of vehicle.veh_id
     *
     * @mbg.generated
     */
    public String getVehId() {
        return vehId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.veh_id
     *
     * @param vehId the value for vehicle.veh_id
     *
     * @mbg.generated
     */
    public void setVehId(String vehId) {
        this.vehId = vehId == null ? null : vehId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.veh_type
     *
     * @return the value of vehicle.veh_type
     *
     * @mbg.generated
     */
    public String getVehType() {
        return vehType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.veh_type
     *
     * @param vehType the value for vehicle.veh_type
     *
     * @mbg.generated
     */
    public void setVehType(String vehType) {
        this.vehType = vehType == null ? null : vehType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.veh_address
     *
     * @return the value of vehicle.veh_address
     *
     * @mbg.generated
     */
    public String getVehAddress() {
        return vehAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.veh_address
     *
     * @param vehAddress the value for vehicle.veh_address
     *
     * @mbg.generated
     */
    public void setVehAddress(String vehAddress) {
        this.vehAddress = vehAddress == null ? null : vehAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.rou_id
     *
     * @return the value of vehicle.rou_id
     *
     * @mbg.generated
     */
    public String getRouId() {
        return rouId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.rou_id
     *
     * @param rouId the value for vehicle.rou_id
     *
     * @mbg.generated
     */
    public void setRouId(String rouId) {
        this.rouId = rouId == null ? null : rouId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.veh_birth
     *
     * @return the value of vehicle.veh_birth
     *
     * @mbg.generated
     */
    public Date getVehBirth() {
        return vehBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.veh_birth
     *
     * @param vehBirth the value for vehicle.veh_birth
     *
     * @mbg.generated
     */
    public void setVehBirth(Date vehBirth) {
        this.vehBirth = vehBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.veh_purchase_date
     *
     * @return the value of vehicle.veh_purchase_date
     *
     * @mbg.generated
     */
    public Date getVehPurchaseDate() {
        return vehPurchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.veh_purchase_date
     *
     * @param vehPurchaseDate the value for vehicle.veh_purchase_date
     *
     * @mbg.generated
     */
    public void setVehPurchaseDate(Date vehPurchaseDate) {
        this.vehPurchaseDate = vehPurchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.veh_remarks
     *
     * @return the value of vehicle.veh_remarks
     *
     * @mbg.generated
     */
    public String getVehRemarks() {
        return vehRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.veh_remarks
     *
     * @param vehRemarks the value for vehicle.veh_remarks
     *
     * @mbg.generated
     */
    public void setVehRemarks(String vehRemarks) {
        this.vehRemarks = vehRemarks == null ? null : vehRemarks.trim();
    }
}