package test.dao;

import java.util.List;
import test.entity.DistributionScope;

public interface DistributionScopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_scope
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer distrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_scope
     *
     * @mbg.generated
     */
    int insert(DistributionScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_scope
     *
     * @mbg.generated
     */
    DistributionScope selectByPrimaryKey(Integer distrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_scope
     *
     * @mbg.generated
     */
    List<DistributionScope> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution_scope
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DistributionScope record);
}