package test.dao;

import java.util.List;
import test.entity.Vehicle;

public interface VehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String vehId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    int insert(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    Vehicle selectByPrimaryKey(String vehId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    List<Vehicle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Vehicle record);
}